project_id = "nvgfgoykyeouwrksszpb"

[functions.send-contact-email]
verify_jwt = false

[functions.portfolio-chatbot]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.index-github-content]
verify_jwt = false

[functions.log-auth-attempt]
verify_jwt = false